-- Huzz Postgres/Supabase schema
-- Run this in Supabase SQL Editor before starting the backend.

BEGIN;

-- Core users
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'organizer' CHECK (role IN ('organizer', 'provider', 'admin')),
  phone VARCHAR(20),
  profile_image VARCHAR(255),
  bio TEXT,
  is_approved BOOLEAN DEFAULT TRUE,
  notification_preferences JSONB,
  privacy_settings JSONB,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_providers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  business_name VARCHAR(255) NOT NULL,
  service_type VARCHAR(100) NOT NULL,
  description TEXT,
  hourly_rate NUMERIC(10, 2),
  min_booking_hours INT DEFAULT 1,
  availability_status VARCHAR(20) DEFAULT 'available' CHECK (availability_status IN ('available', 'unavailable')),
  rating NUMERIC(3, 2) DEFAULT 0,
  total_ratings INT DEFAULT 0,
  profile_image VARCHAR(255),
  portfolio_images JSONB,
  location VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  image_url VARCHAR(255),
  date TIMESTAMPTZ NOT NULL,
  location VARCHAR(255),
  latitude NUMERIC(10, 7),
  longitude NUMERIC(10, 7),
  type VARCHAR(100),
  guest_count INT,
  budget NUMERIC(12, 2),
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending','draft', 'published', 'confirmed', 'ongoing', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(100) NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  image VARCHAR(255),
  phone VARCHAR(30),
  location VARCHAR(255),
  latitude NUMERIC(10, 7),
  longitude NUMERIC(10, 7),
  duration VARCHAR(50),
  availability VARCHAR(50),
  is_approved BOOLEAN DEFAULT FALSE,
  approval_status VARCHAR(20) DEFAULT 'pending' CHECK (approval_status IN ('pending','approved','declined')),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_services_approval_status ON services (approval_status);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  provider_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  organizer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  service_type VARCHAR(100) NOT NULL,
  booking_date TIMESTAMPTZ NOT NULL,
  duration_hours INT,
  total_cost NUMERIC(12, 2),
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'rejected', 'completed', 'cancelled')),
  payment_status VARCHAR(20) DEFAULT 'unpaid' CHECK (payment_status IN ('unpaid', 'paid', 'refunded')),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
  vendor_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  organizer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  booking_date TIMESTAMPTZ NOT NULL,
  notes TEXT,
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'rejected', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vendor_availability_blocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  start_at TIMESTAMPTZ NOT NULL,
  end_at TIMESTAMPTZ NOT NULL,
  source VARCHAR(30) DEFAULT 'manual' CHECK (source IN ('manual', 'calendar_sync', 'booking')),
  source_ref VARCHAR(191),
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'cancelled')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_vendor_availability_vendor_time ON vendor_availability_blocks (vendor_id, start_at, end_at);
CREATE INDEX IF NOT EXISTS idx_vendor_availability_source_ref ON vendor_availability_blocks (source_ref);

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  amount NUMERIC(12, 2) NOT NULL,
  amount_paid NUMERIC(12, 2),
  currency VARCHAR(10),
  payment_method VARCHAR(50),
  transaction_id VARCHAR(255),
  reference VARCHAR(255) UNIQUE,
  metadata JSONB,
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'failed', 'refunded')),
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  ticket_type VARCHAR(100),
  price NUMERIC(10, 2),
  quantity INT,
  sold INT DEFAULT 0,
  qr_code TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ticket_sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  buyer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  quantity INT NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  payment_method VARCHAR(100),
  transaction_id VARCHAR(255),
  qr_code TEXT,
  validated BOOLEAN DEFAULT FALSE,
  validated_at TIMESTAMPTZ,
  validated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  validation_attempts INT DEFAULT 0,
  cancelled_at TIMESTAMPTZ,
  cancellation_reason VARCHAR(255),
  is_refunded BOOLEAN DEFAULT FALSE,
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'failed')),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS event_registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS event_attendees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  name VARCHAR(255),
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  token VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL REFERENCES service_bookings(id) ON DELETE CASCADE,
  reviewer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rating INT CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_reviews_provider_id ON reviews(provider_id);
CREATE INDEX IF NOT EXISTS idx_reviews_rating ON reviews(rating);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  receiver_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS support_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  description VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Compatibility: includes both (category_id, description) and (category, message)
CREATE TABLE IF NOT EXISTS support_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES support_categories(id) ON DELETE SET NULL,
  category VARCHAR(100),
  subject VARCHAR(255) NOT NULL,
  description TEXT,
  message TEXT,
  status VARCHAR(20) DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  priority VARCHAR(20) DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  assigned_to BIGINT REFERENCES users(id) ON DELETE SET NULL,
  sla_response_hours INT DEFAULT 24,
  first_response_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  time_to_respond_minutes INT,
  time_to_resolve_minutes INT,
  sla_breached BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_support_tickets_user_id ON support_tickets(user_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON support_tickets(status);
CREATE INDEX IF NOT EXISTS idx_support_tickets_priority ON support_tickets(priority);
CREATE INDEX IF NOT EXISTS idx_support_tickets_assigned_to ON support_tickets(assigned_to);
CREATE INDEX IF NOT EXISTS idx_support_tickets_created ON support_tickets(created_at);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status_updated ON support_tickets(status, updated_at);

CREATE TABLE IF NOT EXISTS support_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  attachment_path VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_support_messages_ticket_id ON support_messages(ticket_id);
CREATE INDEX IF NOT EXISTS idx_support_messages_user_id ON support_messages(user_id);

CREATE TABLE IF NOT EXISTS faqs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR(100) NOT NULL,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  views INT DEFAULT 0,
  helpful_count INT DEFAULT 0,
  display_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_faqs_category ON faqs(category);
CREATE INDEX IF NOT EXISTS idx_faqs_views ON faqs(views);

CREATE TABLE IF NOT EXISTS ticket_analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
  status_change_from VARCHAR(50),
  status_change_to VARCHAR(50),
  changed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  changed_by BIGINT REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_ticket_analytics_ticket_id ON ticket_analytics(ticket_id);
CREATE INDEX IF NOT EXISTS idx_ticket_analytics_changed_at ON ticket_analytics(changed_at);

CREATE TABLE IF NOT EXISTS ticket_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
  assigned_to BIGINT REFERENCES users(id) ON DELETE SET NULL,
  assigned_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  assigned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  unassigned_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_ticket_assignments_ticket_id ON ticket_assignments(ticket_id);
CREATE INDEX IF NOT EXISTS idx_ticket_assignments_assigned_to ON ticket_assignments(assigned_to);
CREATE INDEX IF NOT EXISTS idx_ticket_assignments_assigned_at ON ticket_assignments(assigned_at);

CREATE TABLE IF NOT EXISTS ticket_refunds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_sale_id BIGINT NOT NULL REFERENCES ticket_sales(id) ON DELETE CASCADE,
  refund_reason VARCHAR(255),
  refund_amount NUMERIC(12, 2) NOT NULL,
  refund_status VARCHAR(20) DEFAULT 'pending' CHECK (refund_status IN ('pending', 'approved', 'rejected', 'completed')),
  requested_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  processed_at TIMESTAMPTZ,
  processed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  notes TEXT
);
CREATE INDEX IF NOT EXISTS idx_ticket_refunds_ticket_sale_id ON ticket_refunds(ticket_sale_id);
CREATE INDEX IF NOT EXISTS idx_ticket_refunds_refund_status ON ticket_refunds(refund_status);
CREATE INDEX IF NOT EXISTS idx_ticket_refunds_requested_at ON ticket_refunds(requested_at);

CREATE TABLE IF NOT EXISTS ticket_waitlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  quantity INT NOT NULL,
  position INT,
  requested_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  notified_at TIMESTAMPTZ,
  purchased BOOLEAN DEFAULT FALSE,
  UNIQUE (ticket_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_ticket_waitlist_ticket_id ON ticket_waitlist(ticket_id);
CREATE INDEX IF NOT EXISTS idx_ticket_waitlist_notified_at ON ticket_waitlist(notified_at);
CREATE INDEX IF NOT EXISTS idx_ticket_waitlist_position ON ticket_waitlist(position);

CREATE TABLE IF NOT EXISTS event_ticket_analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  metric_date DATE NOT NULL,
  tickets_sold INT DEFAULT 0,
  revenue NUMERIC(12, 2) DEFAULT 0,
  refunds_processed INT DEFAULT 0,
  refund_amount NUMERIC(12, 2) DEFAULT 0,
  qr_validations INT DEFAULT 0,
  waitlist_count INT DEFAULT 0,
  UNIQUE (event_id, ticket_id, metric_date)
);
CREATE INDEX IF NOT EXISTS idx_event_ticket_analytics_metric_date ON event_ticket_analytics(metric_date);
CREATE INDEX IF NOT EXISTS idx_event_ticket_analytics_event_id ON event_ticket_analytics(event_id);

CREATE TABLE IF NOT EXISTS ticket_resolution_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric_date DATE NOT NULL UNIQUE,
  total_tickets INT DEFAULT 0,
  tickets_open INT DEFAULT 0,
  tickets_in_progress INT DEFAULT 0,
  tickets_resolved INT DEFAULT 0,
  tickets_closed INT DEFAULT 0,
  avg_resolution_hours NUMERIC(10, 2),
  avg_response_hours NUMERIC(10, 2),
  sla_breached_count INT DEFAULT 0,
  sla_compliance_rate NUMERIC(5, 2)
);
CREATE INDEX IF NOT EXISTS idx_ticket_resolution_metrics_date ON ticket_resolution_metrics(metric_date);

CREATE TABLE IF NOT EXISTS payout_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  requester_role VARCHAR(20) NOT NULL CHECK (requester_role IN ('provider','organizer')),
  source_type VARCHAR(40) NOT NULL CHECK (source_type IN ('service_bookings','ticket_sales')),
  source_event_id BIGINT,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','paid')),
  note TEXT,
  admin_note TEXT,
  requested_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  processed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_payout_requester ON payout_requests (requester_id, requester_role);
CREATE INDEX IF NOT EXISTS idx_payout_status ON payout_requests (status);
CREATE INDEX IF NOT EXISTS idx_payout_source_event ON payout_requests (source_event_id);

-- Seed defaults
INSERT INTO support_categories (name, description) VALUES
  ('Booking Issue', 'Issues related to bookings and reservations'),
  ('Payment Issue', 'Payment and billing related problems'),
  ('Account Issue', 'Account access and profile issues'),
  ('Service Quality', 'Complaints about service quality'),
  ('Other', 'Other issues not listed above')
ON CONFLICT (name) DO NOTHING;

INSERT INTO faqs (category, question, answer) VALUES
  ('Booking', 'How do I book a service?', 'Click on "Browse Vendors", select a vendor, choose a service, and click "Book Now". Fill in your event details and confirm the booking.'),
  ('Booking', 'Can I cancel or reschedule a booking?', 'Yes, you can cancel up to 24 hours before the scheduled date. Contact support if you need to reschedule.'),
  ('Booking', 'What is the refund policy?', 'Refunds are processed within 5-7 business days of cancellation. Cancellations must be made at least 24 hours before the service date.'),
  ('Payments', 'What payment methods do you accept?', 'We accept all major credit cards, debit cards, and digital payment methods through our secure payment gateway.'),
  ('Payments', 'Is my payment information secure?', 'Yes, all payments are processed through encrypted secure channels. We never store your full card details.'),
  ('Account', 'How do I reset my password?', 'Click "Forgot Password" on the login page, enter your email, and follow the reset instructions sent to your email.'),
  ('Account', 'How do I update my profile?', 'Go to Settings > Profile and update your information. Providers can add photos and service details.'),
  ('Vendors', 'How do I become a vendor?', 'Sign up as a Service Provider, complete your profile, add services with details and images, and wait for admin approval.'),
  ('Services', 'How are vendors verified?', 'All vendors go through an approval process. We verify their credentials and reviews before they can offer services.'),
  ('General', 'How do I contact support?', 'You can create a support ticket here, email us, or use the live chat feature available 24/7.')
ON CONFLICT DO NOTHING;

COMMIT;
